### ISSUE TITLE
Fix lint errors

### ISSUE THREAD

**Issue by fhightower** [democritus-project/d8s-strings#14]
HELP WANTED 👋  : If you'd like to take this challenge on, please let me know! Even if you're new to Python and/or Github, this is a great place to start and I'd be happy to help walk you through this challenge as much as you need - don't hesitate to ask.

This particular issue will give you some exposure to fixing [mypy](https://mypy.readthedocs.io/en/stable/) errors.

---

As you can see [here](https://github.com/democritus-project/d8s-strings/runs/2130856860?check_suite_focus=true), the lint step of this library is failing. We want it to pass, so your task, should you choose to accept it, is to fix the lint errors. If you need any guidance, please comment on this issue and we'll be happy to help!

**Comment by raprocks** [comment]
I am taking this on :) will get back with a pull request in a day or two. btw a great project and you have just scored yourself a routine contributor. do tag me where you need any help. Thanks 👍🏼

**Comment by fhightower** [comment]
Thanks @raprocks 🎉 - excited you like the project and find it useful! We have great things planned in the future 🚀

**Comment by raprocks** [comment]
#20 does the job! Please approve the workflows to check the lint status.

**Comment by fhightower** [comment]
🚗 💨  Done! Thank you!!!
